# Generated by Django 3.0.6 on 2020-07-03 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('geeks_field', models.TimeField(auto_now=True)),
                ('videofile', models.FileField(null=True, upload_to='eml/', verbose_name='')),
            ],
        ),
    ]
