# Generated by Django 3.0.6 on 2020-07-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='selector',
            field=models.CharField(default='google', max_length=100),
        ),
    ]
