# Generated by Django 3.0.6 on 2020-07-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_selector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piechart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldmarc_rel', models.BooleanField(default=True)),
            ],
        ),
    ]
